[build]
  command = "cd backend && npm install && npm run build"
  functions = "backend/functions-build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 