[build]
  functions = "functions-build"
  command = "npm install && npm run build"

[dev]
  publish = "public"
  functions = "functions-build"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 